
[functions.signal]
enabled = true
verify_jwt = true
import_map = "./functions/signal/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/signal/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/signal/*.html" ]

[auth.sms]
enable_signup = true

[auth.sms.twilio]
enabled = true
account_sid = "env(TWILIO_ACCOUNT_SID)"
message_service_sid = "env(TWILIO_MESSAGING_SERVICE_SID)"
auth_token = "env(TWILIO_AUTH_TOKEN)"

[functions.alertUser]
enabled = true
verify_jwt = true
import_map = "./functions/alertUser/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/alertUser/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/alertUser/*.html" ]
